### ISSUE TITLE
Deliberate and select a technology for receiving dispatch requests

### ISSUE THREAD

**Issue by amazingproducer** [enderstudy/notification-dispatcher-discord#1]
The method whereby the app will receive dispatch requests is not determined. I'm currently leaning toward using Flask as an API to this end, but a better option may be revealed through discussion.

**Comment by DLMousey** [comment]
I'd probably say the same, can't imagine there'll be a whole lot of endpoints required for this part of the system. I'd probably also say that standard HTTP requests would be the way to go, sockets might be a bit too fiddly to get going with in the beginning.

Push comes to shove and we identify a need for them, we can always add sockets later on.

The way i'm imagining this at the minute is basically a discord bot that exposes an API, we hit the API with some data for the notification and the bot DMs the user with it, you thinking the same thing?

**Comment by amazingproducer** [comment]
Yes. I've amended the documentation to reflect these conclusions.
